# Generated by Django 2.2.3 on 2019-07-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190731_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['publish_date', '-updated', '-timestamp']},
        ),
    ]
